### ISSUE TITLE
may you share code for FFM since there is only code to get FFM data?

### ISSUE THREAD

**Issue by Sandy4321** [diefimov/avito_context_click_2015#1]
https://github.com/diefimov/avito_context_click_2015/blob/master/avito-context-click-py/convert_csv_to_libffm.py

**Comment by diefimov** [comment]
You can find it here: https://github.com/diefimov/avito_context_click_2015/tree/master/fm

**Comment by Sandy4321** [comment]
Dmitry, thanks for soon answer, spasibo
so main file is 
https://github.com/diefimov/avito_context_click_2015/blob/master/fm/src/train.cpp
is it possible to run it on Windows computer?

**Comment by Sandy4321** [comment]
there is a file in your post 
https://github.com/diefimov/avito_context_click_2015/tree/master/data/output-libffm
may you clarify, do you have code for FFM or only for FM

**Comment by Sandy4321** [comment]
and also file 
https://github.com/diefimov/avito_context_click_2015/blob/master/avito-context-click-py/convert_csv_to_libffm.py
